# Generated by Django 2.2 on 2019-12-13 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_surname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher_mark',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
