# Generated by Django 2.2 on 2019-12-13 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20191213_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_student_id',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
